### PR TITLE
Search box for article titles (#105)

### PR DESCRIPTION
**Pull request by erichoog**
@andy5995  so I was working on this and just read your other message referencing this #105 but I hoped it would show you that searching was quite possible while leaving the main infrastructure as is.

Right now this implements AngularJS and the app I built adds in an AngularJS directive that basically allows you to search the title of the articles.

It could be adapted to search the tags as well if needed.  We would just need to remember if we change the article or tag templates then this would need to be updated as well.

### CODE REVIEW

**Comment by andy5995** [comment]
@erichoog Thanks for showing me this.

So, I've tested this patch and I get a search box at the top. But after I type in a word from a title, nothing happens. The letters are showing up in the box, but that's it.

is this intended to search across other pages of the site, or only the page it's on?

**Comment by erichoog** [comment]
It will only search across the page it's on as the app currently only has access to the DOM HTML for the site it's on.  Not sure if it could search across all pages sure it's possible somehow.

Also, just to double check, make sure you've updated the `assests` folder in the tmp directory. I started running `./mhwkb Knowledge _Base/EN tmp && cp -r assets/* tmp/assets` to make sure it always updates that folder.

**Comment by erichoog** [comment]
@andy5995 I've added code to make a `console.log` when the angular app is loaded.

So when you load `index.html` if you go into the Developer Tools in the browser (usually F12) and goto the Console tab you should see no errors and see "SearchBoxApp has started successfully."

**Comment by andy5995** [comment]
>Also, just to double check, make sure you've updated the assests folder in the tmp directory.

I did that, but didn't test this yet.

If this just searches the current page, couldn't that be accomplished by using CTRL-F?

**Comment by erichoog** [comment]
@andy5995 yes that is true lol!  I was going to make it search the tags (and dates before they were removed).  But yes that's true maybe it's not that useful.

Are the other pages just basically an aggregation of atricles for each tag?

I could make an option to search by tag or a drop down list of all the tags to direct you do the different pages.

I guess I had only done this PR because of the issue #105, no worries if it won't get used!

**Comment by andy5995** [comment]
>no worries if it won't get used!

Ok, good!

I didn't realize the ctrl-f thing either when I made the post of about the search box. You're in good company.

>Are the other pages just basically an aggregation of atricles for each tag?

Yes. :)

Try the tag-filtering on http://up-for-grabs.net/#/ 

We'll most likely be switching to Jekyl (#127)

Thanks for working on this demo... I believe we'll still be in need of your skills after a Jekyll switch.

**Comment by erichoog** [comment]
No worries!  I love using Ctrl + F for searching text in the browser and everywhere else too! But I just thought you might want a search feature built into the website.

Working on this helped me to up my HTML parsing skills so it wasn't a waste of time in my books!

Looking forward to seeing the changes with Jekyll!

**Pull request closed without merging**
