### PR TITLE
Articles in Hindi

### PR DESCRIPTION
**Pull request by parthsuresh**
Added two articles in Hindi, one on the effects of cannabis on mental health; and the other on Cognitive Behavioral Therapy.

### CODE REVIEW

**Comment by andy5995** [comment]
Cool!

@parthsuresh Wouldn't they be more accessible from the KB if the titles and the tags were also in Hindi? I was wondering why you chose English.

**Comment by parthsuresh** [comment]
I can do that, shall I send in another PR?

**Comment by andy5995** [comment]
Yah, please, and then go ahead and merge if you're confident. :)

**Comment by andy5995** [comment]
Do you happen to know if we'll have a problem when the `<tag>`.html files are made? Does Linux support all those characters in filenames?

**Comment by parthsuresh** [comment]
Just made a file called चिकित्सा.html . It worked in that case!

**Pull request merged**
